# Book settings
title: "NiPreps"
author: The NiPreps developers
copywright: 2020

# Sphinx customizations
sphinx:
  config:
    html_extra_path: ["assets"]
  extra_extensions:
    - sphinx_exercise

# Execution settings
execute:
  execute_notebooks: auto

# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
  home_page_in_navbar: true

# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab

repository:
  url: https://github.com/nipreps/nipreps-book
  path_to_book: docs
  branch: main

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image